---

- name: Create the user in Postgres
  become     : true
  become_user: postgres
  postgresql_user:
    name    : "{{ repo }}"
    password: "{{ repo }}"

- name: Create the db in Postgres
  become     : true
  become_user: postgres
  postgresql_db:
    name      : "{{ repo }}_db"
    encoding  : UTF-8
    lc_collate: en_US.UTF-8
    lc_ctype  : en_US.UTF-8
    owner     : "{{ repo }}"
